export const mockSettings = [
  {
    id: '1',
    settingKey: 'theme',
    settingLabel: 'Theme',
    category: 'appearance',
    type: 'select',
    value: 'dark',
    description: 'Choose your preferred color theme',
  },
  {
    id: '2',
    settingKey: 'language',
    settingLabel: 'Language',
    category: 'general',
    type: 'select',
    value: 'en',
    description: 'Select your preferred language',
  },
  {
    id: '3',
    settingKey: 'email_notifications',
    settingLabel: 'Email Notifications',
    category: 'notifications',
    type: 'toggle',
    value: 'true',
    description: 'Receive email notifications for important updates',
  },
  {
    id: '4',
    settingKey: 'push_notifications',
    settingLabel: 'Push Notifications',
    category: 'notifications',
    type: 'toggle',
    value: 'true',
    description: 'Enable browser push notifications',
  },
  {
    id: '5',
    settingKey: 'sms_notifications',
    settingLabel: 'SMS Notifications',
    category: 'notifications',
    type: 'toggle',
    value: 'false',
    description: 'Receive SMS alerts for critical events',
  },
  {
    id: '6',
    settingKey: 'public_profile',
    settingLabel: 'Public Profile',
    category: 'privacy',
    type: 'toggle',
    value: 'false',
    description: 'Make your profile visible to other users',
  },
  {
    id: '7',
    settingKey: 'show_email',
    settingLabel: 'Show Email Publicly',
    category: 'privacy',
    type: 'toggle',
    value: 'false',
    description: 'Display your email address on your profile',
  },
  {
    id: '8',
    settingKey: 'two_factor_auth',
    settingLabel: 'Two-Factor Authentication',
    category: 'privacy',
    type: 'toggle',
    value: 'true',
    description: 'Enable 2FA for enhanced account security',
  },
  {
    id: '9',
    settingKey: 'timezone',
    settingLabel: 'Timezone',
    category: 'general',
    type: 'select',
    value: 'UTC',
    description: 'Set your local timezone for date/time displays',
  },
  {
    id: '10',
    settingKey: 'page_size',
    settingLabel: 'Items Per Page',
    category: 'general',
    type: 'number',
    value: '25',
    description: 'Number of items to display per page in lists',
  },
  {
    id: '11',
    settingKey: 'font_size',
    settingLabel: 'Font Size',
    category: 'appearance',
    type: 'select',
    value: 'medium',
    description: 'Adjust the base font size for better readability',
  },
  {
    id: '12',
    settingKey: 'compact_mode',
    settingLabel: 'Compact Mode',
    category: 'appearance',
    type: 'toggle',
    value: 'false',
    description: 'Use compact spacing to fit more content on screen',
  },
  {
    id: '13',
    settingKey: 'session_timeout',
    settingLabel: 'Session Timeout (minutes)',
    category: 'privacy',
    type: 'number',
    value: '30',
    description: 'Automatically log out after period of inactivity',
  },
  {
    id: '14',
    settingKey: 'auto_save',
    settingLabel: 'Auto-Save',
    category: 'general',
    type: 'toggle',
    value: 'true',
    description: 'Automatically save changes as you work',
  },
  {
    id: '15',
    settingKey: 'api_key',
    settingLabel: 'API Key',
    category: 'account',
    type: 'text',
    value: 'sk_test_...',
    description: 'Your API key for external integrations',
  },
]
