import type { Schema } from '@/lib/crudkit/data-provider'

export const productSchema: Schema = {
  title: 'Product',
  idField: 'id',
  fields: [
    {
      name: 'name',
      label: 'Product Name',
      type: 'text',
      required: true,
      sortable: true,
    },
    {
      name: 'sku',
      label: 'SKU',
      type: 'text',
      required: true,
      sortable: true,
    },
    {
      name: 'category',
      label: 'Category',
      type: 'select',
      options: [
        { value: 'electronics', label: 'Electronics' },
        { value: 'clothing', label: 'Clothing' },
        { value: 'sports', label: 'Sports' },
        { value: 'home', label: 'Home & Garden' },
        { value: 'books', label: 'Books' },
      ],
      required: true,
      filterable: true,
      sortable: true,
    },
    {
      name: 'price',
      label: 'Price ($)',
      type: 'number',
      required: true,
      sortable: true,
    },
    {
      name: 'stock',
      label: 'Stock',
      type: 'number',
      required: true,
      sortable: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'active', label: 'Active' },
        { value: 'discontinued', label: 'Discontinued' },
        { value: 'out-of-stock', label: 'Out of Stock' },
      ],
      required: true,
      filterable: true,
      sortable: true,
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      showOnCreate: true,
      showOnEdit: true,
    },
  ],
}

export const mockProducts = [
  {
    id: '1',
    name: 'Wireless Headphones',
    sku: 'WH-001',
    category: 'electronics',
    price: 79.99,
    stock: 45,
    status: 'active',
    description: 'Premium wireless headphones with noise cancellation',
  },
  {
    id: '2',
    name: 'Cotton T-Shirt',
    sku: 'CT-101',
    category: 'clothing',
    price: 19.99,
    stock: 120,
    status: 'active',
    description: '100% organic cotton, available in multiple colors',
  },
  {
    id: '3',
    name: 'Yoga Mat',
    sku: 'YM-301',
    category: 'sports',
    price: 24.99,
    stock: 0,
    status: 'out-of-stock',
    description: 'Non-slip yoga mat, 6mm thick',
  },
  {
    id: '4',
    name: 'Smart Watch',
    sku: 'SW-202',
    category: 'electronics',
    price: 199.99,
    stock: 30,
    status: 'active',
    description: 'Fitness tracker with heart rate monitor',
  },
  {
    id: '5',
    name: 'Running Shoes',
    sku: 'RS-401',
    category: 'sports',
    price: 89.99,
    stock: 55,
    status: 'active',
    description: 'Lightweight running shoes with cushioned sole',
  },
  {
    id: '6',
    name: 'Coffee Maker',
    sku: 'CM-501',
    category: 'home',
    price: 49.99,
    stock: 25,
    status: 'active',
    description: 'Programmable coffee maker, 12-cup capacity',
  },
  {
    id: '7',
    name: 'Novel - The Great Adventure',
    sku: 'BK-601',
    category: 'books',
    price: 14.99,
    stock: 100,
    status: 'active',
    description: 'Bestselling fiction novel',
  },
  {
    id: '8',
    name: 'Bluetooth Speaker',
    sku: 'BS-103',
    category: 'electronics',
    price: 39.99,
    stock: 0,
    status: 'discontinued',
    description: 'Portable bluetooth speaker - discontinued model',
  },
  {
    id: '9',
    name: 'Denim Jeans',
    sku: 'DJ-201',
    category: 'clothing',
    price: 59.99,
    stock: 75,
    status: 'active',
    description: 'Classic fit denim jeans',
  },
  {
    id: '10',
    name: 'Tennis Racket',
    sku: 'TR-402',
    category: 'sports',
    price: 129.99,
    stock: 18,
    status: 'active',
    description: 'Professional-grade tennis racket',
  },
  {
    id: '11',
    name: 'Garden Hose',
    sku: 'GH-502',
    category: 'home',
    price: 29.99,
    stock: 40,
    status: 'active',
    description: '50ft expandable garden hose',
  },
  {
    id: '12',
    name: 'Cookbook - Italian Cuisine',
    sku: 'BK-602',
    category: 'books',
    price: 24.99,
    stock: 60,
    status: 'active',
    description: 'Authentic Italian recipes',
  },
  {
    id: '13',
    name: 'Laptop Stand',
    sku: 'LS-104',
    category: 'electronics',
    price: 34.99,
    stock: 90,
    status: 'active',
    description: 'Adjustable aluminum laptop stand',
  },
  {
    id: '14',
    name: 'Winter Jacket',
    sku: 'WJ-301',
    category: 'clothing',
    price: 149.99,
    stock: 35,
    status: 'active',
    description: 'Waterproof winter jacket with insulation',
  },
  {
    id: '15',
    name: 'Dumbbells Set',
    sku: 'DS-501',
    category: 'sports',
    price: 79.99,
    stock: 22,
    status: 'active',
    description: 'Adjustable dumbbells, 5-25 lbs',
  },
]
