export const mockTasks = [
  {
    id: '1',
    title: 'Design new landing page',
    status: 'todo',
    priority: 'high',
    assignee: 'John Doe',
    description: 'Create mockups for the new marketing landing page',
  },
  {
    id: '2',
    title: 'Fix login bug',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Jane Smith',
    description: 'Users unable to login with special characters in password',
  },
  {
    id: '3',
    title: 'Update documentation',
    status: 'todo',
    priority: 'low',
    assignee: 'Bob Johnson',
    description: 'Update API documentation with new endpoints',
  },
  {
    id: '4',
    title: 'Code review',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Alice Williams',
    description: 'Review PR #234 for the payment module',
  },
  {
    id: '5',
    title: 'Deploy to staging',
    status: 'done',
    priority: 'medium',
    assignee: 'Charlie Brown',
    description: 'Deploy latest changes to staging environment',
  },
  {
    id: '6',
    title: 'Write unit tests',
    status: 'todo',
    priority: 'medium',
    assignee: 'John Doe',
    description: 'Add unit tests for the new user service',
  },
  {
    id: '7',
    title: 'Customer feedback analysis',
    status: 'done',
    priority: 'low',
    assignee: 'Jane Smith',
    description: 'Analyze Q4 customer feedback surveys',
  },
  {
    id: '8',
    title: 'Implement search feature',
    status: 'todo',
    priority: 'high',
    assignee: 'David Lee',
    description: 'Add full-text search across all entities',
  },
  {
    id: '9',
    title: 'Optimize database queries',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Emma Wilson',
    description: 'Improve query performance on user dashboard',
  },
  {
    id: '10',
    title: 'Security audit',
    status: 'done',
    priority: 'high',
    assignee: 'Frank Miller',
    description: 'Complete quarterly security audit',
  },
]
