export const mockUsers = [
  { id: '1', name: 'John Doe', email: 'john@example.com', role: 'admin', status: 'active', department: 'Engineering' },
  { id: '2', name: 'Jane Smith', email: 'jane@example.com', role: 'user', status: 'active', department: 'Marketing' },
  { id: '3', name: 'Bob Johnson', email: 'bob@example.com', role: 'user', status: 'inactive', department: 'Sales' },
  { id: '4', name: 'Alice Williams', email: 'alice@example.com', role: 'admin', status: 'active', department: 'Engineering' },
  { id: '5', name: 'Charlie Brown', email: 'charlie@example.com', role: 'guest', status: 'active', department: 'Support' },
  { id: '6', name: 'David Lee', email: 'david@example.com', role: 'user', status: 'active', department: 'Engineering' },
  { id: '7', name: 'Emma Wilson', email: 'emma@example.com', role: 'admin', status: 'active', department: 'Marketing' },
  { id: '8', name: 'Frank Miller', email: 'frank@example.com', role: 'user', status: 'inactive', department: 'Sales' },
  { id: '9', name: 'Grace Taylor', email: 'grace@example.com', role: 'user', status: 'active', department: 'Support' },
  { id: '10', name: 'Henry Davis', email: 'henry@example.com', role: 'guest', status: 'active', department: 'Engineering' },
  { id: '11', name: 'Isabel Martinez', email: 'isabel@example.com', role: 'user', status: 'active', department: 'Marketing' },
  { id: '12', name: 'Jack Anderson', email: 'jack@example.com', role: 'admin', status: 'active', department: 'Engineering' },
  { id: '13', name: 'Karen Thomas', email: 'karen@example.com', role: 'user', status: 'inactive', department: 'Sales' },
  { id: '14', name: 'Leo Jackson', email: 'leo@example.com', role: 'user', status: 'active', department: 'Support' },
  { id: '15', name: 'Maria Garcia', email: 'maria@example.com', role: 'admin', status: 'active', department: 'Marketing' },
  { id: '16', name: 'Nathan White', email: 'nathan@example.com', role: 'guest', status: 'active', department: 'Engineering' },
  { id: '17', name: 'Olivia Harris', email: 'olivia@example.com', role: 'user', status: 'active', department: 'Sales' },
  { id: '18', name: 'Paul Martin', email: 'paul@example.com', role: 'user', status: 'inactive', department: 'Support' },
  { id: '19', name: 'Quinn Robinson', email: 'quinn@example.com', role: 'admin', status: 'active', department: 'Engineering' },
  { id: '20', name: 'Rachel Clark', email: 'rachel@example.com', role: 'user', status: 'active', department: 'Marketing' },
  { id: '21', name: 'Sam Rodriguez', email: 'sam@example.com', role: 'guest', status: 'active', department: 'Sales' },
  { id: '22', name: 'Tina Lewis', email: 'tina@example.com', role: 'user', status: 'active', department: 'Support' },
  { id: '23', name: 'Uma Walker', email: 'uma@example.com', role: 'admin', status: 'inactive', department: 'Engineering' },
  { id: '24', name: 'Victor Hall', email: 'victor@example.com', role: 'user', status: 'active', department: 'Marketing' },
  { id: '25', name: 'Wendy Allen', email: 'wendy@example.com', role: 'user', status: 'active', department: 'Sales' },
]
