export const mockOrders = [
  {
    id: '1',
    orderNumber: 'ORD-2024-001',
    customer: 'John Smith',
    email: 'john.smith@email.com',
    total: 299.97,
    status: 'delivered',
    date: '2024-01-15',
    items: 'Wireless Headphones, Smart Watch',
  },
  {
    id: '2',
    orderNumber: 'ORD-2024-002',
    customer: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    total: 149.98,
    status: 'shipped',
    date: '2024-01-18',
    items: 'Cotton T-Shirt x2, Running Shoes',
  },
  {
    id: '3',
    orderNumber: 'ORD-2024-003',
    customer: 'Michael Brown',
    email: 'mbrown@email.com',
    total: 79.99,
    status: 'processing',
    date: '2024-01-20',
    items: 'Yoga Mat, Water Bottle',
  },
  {
    id: '4',
    orderNumber: 'ORD-2024-004',
    customer: 'Emily Davis',
    email: 'emily.d@email.com',
    total: 524.96,
    status: 'pending',
    date: '2024-01-22',
    items: 'Laptop Stand, Wireless Mouse, Keyboard',
  },
  {
    id: '5',
    orderNumber: 'ORD-2024-005',
    customer: 'David Wilson',
    email: 'dwilson@email.com',
    total: 199.99,
    status: 'cancelled',
    date: '2024-01-23',
    items: 'Coffee Maker',
  },
  {
    id: '6',
    orderNumber: 'ORD-2024-006',
    customer: 'Lisa Martinez',
    email: 'lisa.m@email.com',
    total: 89.99,
    status: 'delivered',
    date: '2024-01-25',
    items: 'Novel, Cookbook',
  },
  {
    id: '7',
    orderNumber: 'ORD-2024-007',
    customer: 'James Taylor',
    email: 'jtaylor@email.com',
    total: 449.97,
    status: 'shipped',
    date: '2024-01-26',
    items: 'Tennis Racket, Dumbbells Set, Yoga Mat',
  },
  {
    id: '8',
    orderNumber: 'ORD-2024-008',
    customer: 'Jennifer White',
    email: 'jwhite@email.com',
    total: 169.98,
    status: 'processing',
    date: '2024-01-27',
    items: 'Winter Jacket',
  },
  {
    id: '9',
    orderNumber: 'ORD-2024-009',
    customer: 'Robert Garcia',
    email: 'rgarcia@email.com',
    total: 59.99,
    status: 'pending',
    date: '2024-01-28',
    items: 'Denim Jeans',
  },
  {
    id: '10',
    orderNumber: 'ORD-2024-010',
    customer: 'Maria Rodriguez',
    email: 'maria.r@email.com',
    total: 129.98,
    status: 'delivered',
    date: '2024-01-29',
    items: 'Garden Hose, Plant Pots',
  },
]
