export const mockPosts = [
  {
    id: '1',
    title: 'Getting Started with React 19',
    author: 'Jane Developer',
    category: 'technology',
    status: 'published',
    publishDate: '2024-01-15',
    excerpt: 'Explore the new features in React 19 and how to use them in your projects.',
    content: 'React 19 brings exciting new features...',
  },
  {
    id: '2',
    title: 'Building a Successful Startup',
    author: 'Mike Entrepreneur',
    category: 'business',
    status: 'published',
    publishDate: '2024-01-18',
    excerpt: 'Lessons learned from founding and scaling a tech startup.',
    content: 'Starting a business is challenging but rewarding...',
  },
  {
    id: '3',
    title: 'Minimalist Living Guide',
    author: 'Sarah Lifestyle',
    category: 'lifestyle',
    status: 'draft',
    publishDate: '2024-01-20',
    excerpt: 'How to declutter your life and focus on what matters.',
    content: 'Minimalism is about living with intention...',
  },
  {
    id: '4',
    title: 'Hidden Gems in Tokyo',
    author: 'Travel Explorer',
    category: 'travel',
    status: 'published',
    publishDate: '2024-01-22',
    excerpt: 'Discover the lesser-known attractions in Japan\'s capital.',
    content: 'Tokyo has so much more to offer beyond the tourist spots...',
  },
  {
    id: '5',
    title: 'Mastering Italian Pasta',
    author: 'Chef Maria',
    category: 'food',
    status: 'published',
    publishDate: '2024-01-25',
    excerpt: 'Learn to make authentic Italian pasta from scratch.',
    content: 'Making pasta at home is easier than you think...',
  },
  {
    id: '6',
    title: 'AI and the Future of Work',
    author: 'Jane Developer',
    category: 'technology',
    status: 'published',
    publishDate: '2024-01-27',
    excerpt: 'How artificial intelligence is transforming the workplace.',
    content: 'AI is reshaping how we work and collaborate...',
  },
  {
    id: '7',
    title: 'Effective Team Management',
    author: 'Mike Entrepreneur',
    category: 'business',
    status: 'draft',
    publishDate: '2024-01-29',
    excerpt: 'Strategies for building and leading high-performing teams.',
    content: 'Great teams don\'t happen by accident...',
  },
  {
    id: '8',
    title: 'Morning Routine for Success',
    author: 'Sarah Lifestyle',
    category: 'lifestyle',
    status: 'published',
    publishDate: '2024-01-30',
    excerpt: 'Start your day right with these proven morning habits.',
    content: 'A good morning routine sets the tone for the entire day...',
  },
  {
    id: '9',
    title: 'Budget Travel in Europe',
    author: 'Travel Explorer',
    category: 'travel',
    status: 'published',
    publishDate: '2024-02-01',
    excerpt: 'How to explore Europe without breaking the bank.',
    content: 'Traveling Europe on a budget is absolutely possible...',
  },
  {
    id: '10',
    title: 'Sourdough Bread Basics',
    author: 'Chef Maria',
    category: 'food',
    status: 'archived',
    publishDate: '2023-12-15',
    excerpt: 'The complete guide to baking sourdough bread at home.',
    content: 'Sourdough baking is an art and a science...',
  },
]
